// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnlphOLXgUoDvXim5H8IA9CUbX7_ipK4c',
    appId: '1:146195934050:web:a04b6a79dc8353e7bd1a3b',
    messagingSenderId: '146195934050',
    projectId: 'tns-notif',
    authDomain: 'tns-notif.firebaseapp.com',
    storageBucket: 'tns-notif.firebasestorage.app',
    measurementId: 'G-T7XPEBE2QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGT9GNKDXVaSAadJkzlssX2q_bOXm0sCk',
    appId: '1:146195934050:android:e63e5e16d8eb9300bd1a3b',
    messagingSenderId: '146195934050',
    projectId: 'tns-notif',
    storageBucket: 'tns-notif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo3BeUjEWDWNYMW5pHSIJumU64Q1oYlso',
    appId: '1:146195934050:ios:e8187cbaae752c80bd1a3b',
    messagingSenderId: '146195934050',
    projectId: 'tns-notif',
    storageBucket: 'tns-notif.firebasestorage.app',
    iosBundleId: 'com.tnsgroup.tnsMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo3BeUjEWDWNYMW5pHSIJumU64Q1oYlso',
    appId: '1:146195934050:ios:e8187cbaae752c80bd1a3b',
    messagingSenderId: '146195934050',
    projectId: 'tns-notif',
    storageBucket: 'tns-notif.firebasestorage.app',
    iosBundleId: 'com.tnsgroup.tnsMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnlphOLXgUoDvXim5H8IA9CUbX7_ipK4c',
    appId: '1:146195934050:web:aa6a1d52029030b3bd1a3b',
    messagingSenderId: '146195934050',
    projectId: 'tns-notif',
    authDomain: 'tns-notif.firebaseapp.com',
    storageBucket: 'tns-notif.firebasestorage.app',
    measurementId: 'G-QNBTE2QNKB',
  );
}
